name: build

on:
  push

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os:
          - windows
          - ubuntu
          - macOS
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Setup
        uses: jiro4989/setup-nim-action@v1
      
      - name: Build
        run: nimble build -Y
      
      - name: Package
        uses: actions/upload-artifact@v3
        with:
          name: null0-${{ matrix.os }}
          path: |
            null0
            null0.exe
            *.null0
